apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: google-secretstore
  namespace: keycloak
spec:
  provider:
      gcpsm:                                  # gcpsm provider
        auth:
          secretRef:
            secretAccessKeySecretRef:
              name: gcpsm-secret              # secret name containing SA key
              key: secret-access-credentials  # key name containing SA key
        projectID: vipscanner-1248                  # name of Google Cloud project

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgresql-data
  namespace: keycloak
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: google-secretstore
  target:
    name: keycloak-postgresql-external-secrets
    creationPolicy: Owner
  data:
  - secretKey: password  # name of the GCPSM secret key
    remoteRef:
      key: keycloak-password
  - secretKey: postgres-password  # name of the GCPSM secret key
    remoteRef:
      key: keycloak-postgresql-password
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: keycload-data
  namespace: keycloak
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: google-secretstore
  target:
    name: keycloak-external-secrets
    creationPolicy: Owner
  data:
  - secretKey: admin-password  # name of the GCPSM secret key
    remoteRef:
      key: keycloak-admin-password

# External HA Postgres credentials 
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-postgresql-data
  namespace: keycloak
spec:
  refreshInterval: 1h           # rate SecretManager pulls GCPSM
  secretStoreRef:
    kind: SecretStore
    name: google-secretstore               # name of the SecretStore (or kind specified)
  target:
    name: external-postgresql-data  # name of the k8s Secret to be created
    creationPolicy: Owner
  data:
  - secretKey: password  # name of the GCPSM secret key
    remoteRef:
      key: vikunja-postgresql-password
  - secretKey: repmgr-password  # name of the GCPSM secret key
    remoteRef:
      key: vikunja-postgresql-repmgr-password