apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: google-secretstore
  namespace: vikunja-demo
spec:
  provider:
      gcpsm:                                  # gcpsm provider
        auth:
          secretRef:
            secretAccessKeySecretRef:
              name: gcpsm-secret              # secret name containing SA key
              key: secret-access-credentials  # key name containing SA key
        projectID: REPLACE_TO_PROJECT_ID                 # name of Google Cloud project

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgresql-data
  namespace: vikunja-demo
spec:
  refreshInterval: 1h           # rate SecretManager pulls GCPSM
  secretStoreRef:
    kind: SecretStore
    name: google-secretstore               # name of the SecretStore (or kind specified)
  target:
    name: postgresql-credentials  # name of the k8s Secret to be created
    creationPolicy: Owner
  data:
  - secretKey: password  # name of the GCPSM secret key
    remoteRef:
      key: vikunja-postgresql-password
  - secretKey: repmgr-password  # name of the GCPSM secret key
    remoteRef:
      key: vikunja-postgresql-repmgr-password

---
apiVersion: v1
stringData:
  api-config.yaml: |-
    auth:
      local:
        enabled: false
      openid:
        enabled: true
        redirecturl: http://vikunja.127-0-0-1.sslip.io/auth/openid/
        providers:
          - name: keycloak
            authurl: http://keycloak.127-0-0-1.sslip.io/realms/master # This is not working within the cluster because resolves to 127.0.0.1
            clientid: vikunja
            clientsecret: Pp8hRKMVWskAoL5ecYM1yE0Ms1832SWn # According docs, this secret cannot be in external variables. Todo: move Vikunja config to External Secrets Manager from Repo
    metrics:
      enabled: true
    cache:
      enabled: true
      type: redis
    cors:
      enable: false
      origins: []
    database:
      type: postgres
    defaultsettings:
      avatar_provider: gravatar
      discoverable_by_email: true
      discoverable_by_name: true
      week_start: 1
    files:
      basepath: /files
    log:
      path: null
    mailer:
      enabled: false
    redis:
      db: 0
      enabled: false
      host: ""
      password: ""
    service:
      JWTSecret: ""
      enableregistration: true
      frontendurl: ""
      interface: :3456
      timezone: GMT
kind: Secret
metadata:
  name: vikunja
  namespace: vikunja-demo
type: Opaque