apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak-secrets
spec:
  destination:
    name: ''
    namespace: keycloak
    server: 'https://kubernetes.default.svc'
  source:
    # This is the path to the kustomization.yaml file for PROD environment  
    path: manifests/keycloak/overlays/prod
    repoURL: 'https://github.com/zsozso2210/vikunja-kubernetes.git'
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - ApplyOutOfSyncOnly=true