apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vikunja-todo
spec:
  destination:
    name: ''
    namespace: vikunja-demo
    server: 'https://kubernetes.default.svc'
  source:
    # This is the path to the kustomization.yaml file for PROD environment  
    path: /manifests/vikunja/overlays/prod
    repoURL: 'https://github.com/zsozso2210/vikunja-kubernetes'
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - ApplyOutOfSyncOnly=true