apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: vikunja
    app.kubernetes.io/name: vikunja
  name: vikunja-api
spec:
  replicas: 1 # Replica count is adjusted in the overlays
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/component: api
      app.kubernetes.io/instance: vikunja
      app.kubernetes.io/name: vikunja
  template:
    metadata:
      labels:
        app.kubernetes.io/component: api
        app.kubernetes.io/instance: vikunja
        app.kubernetes.io/name: vikunja
    spec:
      # Priority Classes are used to order the scheduling queue in Kubernetes
      priorityClassName: high-priority
      # Vikunja API is not able to resolve the keycloak hostname within the cluster
      hostAliases:
      - ip: "10.96.44.39" # Static IP of the 'keycloak' service in 'keycloak' namespace
        hostnames:
        - "keycloak.127-0-0-1.sslip.io"
      containers:
        - env:
          - name: VIKUNJA_DATABASE_USER
            value: "postgres" # Todo: move to secret
          - name: VIKUNJA_DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgresql-credentials
                key: password
          - name: VIKUNJA_DATABASE_HOST
            value: "postgresql-ha-pgpool" 
          - name: VIKUNJA_SERVICE_JWTSECRET
            valueFrom:
              secretKeyRef:
                name: postgresql-credentials
                key: repmgr-password # Todo: Change it to JWTSecret
          - name: VIKUNJA_SERVICE_FRONTENDURL
            value: http://vikunja.127-0-0-1.sslip.io/
          image: 'vikunja/api:latest'
          imagePullPolicy: IfNotPresent
          # QoS class of the Pod is Quaranteed because it has a memory request and a memory limit
          # We use the same values for limits and requests to ensure that the pods are not evicted
          resources:
            limits:
              cpu: '1'
              memory: 512Mi
            requests:
              cpu: '1'
              memory: 512Mi
          name: api
          ports:
            - containerPort: 3456
              name: http
              protocol: TCP
          startupProbe:
            periodSeconds: 5
            failureThreshold: 10
            httpGet:
              path: /health
              port: 3456
          readinessProbe:
            periodSeconds: 5
            failureThreshold: 10
            httpGet:
              path: /health
              port: 3456
          livenessProbe:
            periodSeconds: 5
            failureThreshold: 10
            httpGet:
              path: /health
              port: 3456
          securityContext:
            capabilities:
              add:
                - CAP_CHOWN
          volumeMounts:
            - mountPath: /tmp
              name: tmp
            - mountPath: /etc/vikunja/config.yaml
              name: api-config
              subPath: api-config.yaml
      serviceAccountName: vikunja
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: worker-node
                operator: In
                values:
                - 'true'
        # podAffinity is set to ensure that the api pods are not scheduled on the same node with other api pods
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app.kubernetes.io/component 
                operator: In
                values:
                - api
            topologyKey: "kubernetes.io/hostname"
        # podAffinity is set to ensure that the api pods are scheduled on the same node as the frontend pods
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app.kubernetes.io/component
                operator: In
                values:
                - frontend
            topologyKey: "kubernetes.io/hostname"
      # The tolerations are set to ensure that the api pods spread accross the worker nodes
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app.kubernetes.io/component: api
      volumes:
        - emptyDir: {}
          name: tmp
        - name: api-config
          secret:
            secretName: vikunja
