apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: vikunja-api-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: vikunja-api
  minReplicas: 1 # Minimum number of replicas is adjusted in the overlays 
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
