apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


resources:
- ../../base
labels:
- includeSelectors: true
  pairs:
    environment: prod

patches:
  - target:
      kind: Deployment
      name: vikunja-api
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 2
  - target:
      kind: Deployment
      name: vikunja-frontend
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 2